prey_population_size: 200
predator_population_size: 1

speed: 2
vision: 15
separation: 3
cohere: 0.0
separate: 0.5
match: 1.0

predator_speed: 4
predator_vision: 30
width: 300
height: 300

threshold: 10
predator_introduce_time: 100